version: '3.3'
services:
  chainlink-node:
    image: smartcontract/chainlink:2.3.0
    # environment:
    #   ROOT: ${ROOT}
    #   LOG_LEVEL: ${LOG_LEVEL}
    #   ETH_CHAIN_ID: ${ETH_CHAIN_ID}
    #   CHAINLINK_TLS_PORT: ${CHAINLINK_TLS_PORT}
    #   SECURE_COOKIES: ${SECURE_COOKIES}
    #   ALLOW_ORIGINS: ${ALLOW_ORIGINS}
    #   ETH_URL: ${ETH_URL}
    #   DATABASE_URL: ${DATABASE_URL}
    restart: on-failure
    ports:
      - '6688:6688'
    volumes:
      - ${CHAINLINK_DATA}/:/chainlink/
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    command: node -config /chainlink/config.toml -secrets /chainlink/secrets.toml start -a /chainlink/.api
    networks:
      - chainlink

networks:
  chainlink:
    external: true