version: '3.3'
services:
  chainlink-postgresql:
    image: postgres:15.5
    volumes:
      - database:/opt/postgres/data
    environment:
      ALLOW_IP_RANGE: 0.0.0.0/0
      DEFAULT_ENCODING: UTF8
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '6432:5432'
    restart: on-failure
    networks:
      - chainlink

volumes:
  database:
networks:
  chainlink:
    external: true